services:
  server:
    platform: linux/arm64
    hostname: server
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        PYTHON_VERSION: 3.9.16
        POETRY_VERSION: 1.5.1
    ports:
      - 8010:8000
    volumes:
      - .:/workdir
    networks:
      - server
    command: ["src", "trade"]


networks:
  server:
    name: server
    driver: bridge
